[workspace]
members = ["proc-macro"]

[package]
name = "fn-bnf"
version = "0.1.0"
edition = "2021"

[features]
more_tuple_impls = []
__internal_test_docs = []

[dependencies]
fn-bnf-macro = { path = "./proc-macro" }